defmodule RecordVerifier.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:beneficiaries) do
      modify :spread_sheet_id, :text, null: true
      add :committer, :text, null: false
    end
  end

  def down do
    alter table(:beneficiaries) do
      remove :committer
      modify :spread_sheet_id, :text, null: false
    end
  end
end
