defmodule RecordVerifier.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:beneficiaries, [:spread_sheet_id],
             name: "beneficiaries_unique_spread_sheet_id_per_beneficiary_index"
           )
  end

  def down do
    drop_if_exists unique_index(:beneficiaries, [:spread_sheet_id],
                     name: "beneficiaries_unique_spread_sheet_id_per_beneficiary_index"
                   )
  end
end
