defmodule RecordVerifier.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:beneficiaries, [:id_number],
                     name: "beneficiaries_unique_id_number_per_beneficiary_index"
                   )
  end

  def down do
    create unique_index(:beneficiaries, [:id_number],
             name: "beneficiaries_unique_id_number_per_beneficiary_index"
           )
  end
end
