defmodule RecordVerifier.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:beneficiaries, [:first_name, :middle_name, :last_name],
             name: "beneficiaries_unique_combination_of_names_per_beneficiary_index"
           )
  end

  def down do
    drop_if_exists unique_index(:beneficiaries, [:first_name, :middle_name, :last_name],
                     name: "beneficiaries_unique_combination_of_names_per_beneficiary_index"
                   )
  end
end
