defmodule RecordVerifier.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:beneficiaries) do
      add :spread_sheet_id, :text, null: false
    end
  end

  def down do
    alter table(:beneficiaries) do
      remove :spread_sheet_id
    end
  end
end
