defmodule RecordVerifier.Repo.Migrations.AddBeneficiaries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:beneficiaries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :first_name, :text, null: false
      add :middle_name, :text, null: false
      add :last_name, :text, null: false
      add :birth_date, :date, null: false
      add :barangay, :text, null: false
      add :city_or_municipality, :text, null: false
      add :province, :text, null: false
      add :district, :text, null: false
      add :id_type, :text, null: false
      add :id_number, :text, null: false
      add :place_of_issue, :text, null: false
      add :contact_number, :text, null: false
      add :beneficiary_type, :text, null: false
      add :occupation, :text, null: false
      add :sex, :text, null: false
      add :civil_status, :text, null: false
      add :age, :bigint, null: false
      add :monthly_income, :money_with_currency, null: false
      add :dependent, :text, null: false
      add :interested, :boolean, null: false
      add :skills_needed, :boolean, null: false
    end

    create unique_index(:beneficiaries, [:id_number],
             name: "beneficiaries_unique_id_number_per_beneficiary_index"
           )
  end

  def down do
    drop_if_exists unique_index(:beneficiaries, [:id_number],
                     name: "beneficiaries_unique_id_number_per_beneficiary_index"
                   )

    drop table(:beneficiaries)
  end
end
